site_name: Recap Time Probot App User Manual
site_url: https://probot-docs.recaptime.tk
nav:
    - Home: index.md
    - 'Getting Started': getting-started.md
    - About: about.md
    - 'Get Support': support.md
theme: readthedocs
repo_url: https://gitlab.com/MadeByThePinsTeam/probot-docs.recaptime.tk