site_name: Recap Time Probot App User Manual
nav:
    - Home: index.md
    - 'Getting Started': getting-started.md
    - About: about.md
    - 
theme: readthedocs
repo_url: https://gitlab.com/MadeByThePinsTeam/probot-docs.recaptime.tk
